Add muon pt correction systematic
ExtraYukawa/Script_ForMVA pull request #15
Opened 2022-10-13 14:13 UTC by AlbertHsuNTUphys

Only test step1, step2 need samples to test.

2022-10-13 14:14 UTC, AlbertHsuNTUphys commented
@gourangakole @menglu21 please tell me if there is any problems. Thank you.

2022-10-13 14:30 UTC, gourangakole commented
Hi @AlbertHsuNTUphys thank you! ..I made one comment on the code..please check.

2022-10-13 14:43 UTC, gourangakole requested changes

2022-10-13 14:43 UTC, gourangakole commented on BDT_application/step2_BDTapplication_condor/TMVAClassificationApplication.C
> -   theTree->SetBranchAddress( "ttc_mll", &ttc_mll);
Hi @AlbertHsuNTUphys why did you remove this and instead put the setbranch address in every variation?

2022-10-13 14:59 UTC, gourangakole commented on BDT_application/step2_BDTapplication_condor/TMVAClassificationApplication.C
> -   theTree->SetBranchAddress( "ttc_mll", &ttc_mll);
After the discussion with @AlbertHsuNTUphys its more clear now

2022-10-14 08:17 UTC, menglu21 commented
> @gourangakole @menglu21 please tell me if there is any problems. Thank you.

Hi @AlbertHsuNTUphys thanks for the update, by eye they look fine to me.

2022-10-14 10:18 UTC, merged